<?php echo $this->doctype(); ?>
<html lang="en" ng-app="OnyxAdmin" class="no-js">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Onyx System -> Admin'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/vendor/paul-headington/OnyxAdmin/css/OnyxAdmin.css')
                        ->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css')
                        ->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css') 
                        ; ?>
        
        <!-- Scripts -->
        <?php echo $this->headScript()                            
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <!-- jQuery -->
          <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
          <!-- jQuery UI -->
          <script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
          <!-- TinyMCE -->
          <script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
    </head>
    <body>  
          <!--[if lt IE 7]>
                <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
            <![endif]-->
      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="<?php echo $this->basePath('vendor/paul-headington/OnyxAdmin/img/colenso_logo.png') ?>" alt="Colenso BBDO" width="138px"/>&nbsp;Onyx Admin</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#/home">Dashboard</a></li>
            <li><a href="#/settings">Settings</a></li>
            <li><a href="/user/logout">Logout</a></li>
            <li><a href="mailto:paul.headington@colensobbdo.co.nz">Help</a></li>
          </ul>          
        </div>
      </div>
    </div>        
        <div class="container-fluid"  ng-view>            
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2009 - <?php echo date('Y') ?> Paul Headington. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript()
                ->prependFile('/vendor/paul-headington/OnyxAdmin/OnyxAdmin.js')
                ->prependFile('/vendor/paul-headington/OnyxAdmin/controllers/TipsController.js')
                ->prependFile('/vendor/paul-headington/OnyxAdmin/controllers/HomeController.js')
                ->prependFile('/vendor/paul-headington/OnyxAdmin/controllers/SettingsController.js')
                ->prependFile('/vendor/paul-headington/OnyxAdmin/components/version/interpolate-filter.js')
                ->prependFile('/vendor/paul-headington/OnyxAdmin/components/version/version-directive.js')
                ->prependFile('/vendor/paul-headington/OnyxAdmin/components/version/version.js')                
                ->prependFile('/vendor/paul-headington/OnyxAdmin/bower_components/angular-route/angular-route.js')
                ->prependFile('/vendor/paul-headington/OnyxAdmin/bower_components/angular/angular.js')
                // use this in production
                //->prependFile('//ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js')                      
                ;?>        
    </body>
</html>
